language: elixir
elixir: '1.10.2'
otp_release: '22.2.8'
env:
  - MIX_ENV=test

cache:
  directories:
    - _build
    - deps

script:
  - mix coveralls
  - mix credo --strict
  - mix format --check-formatted
